//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace istoCPos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriRapor
    {
        public int Id { get; set; }
        public string islemNo { get; set; }
        public string EvrakNo { get; set; }
        public string islemTuru { get; set; }
        public string islemTarihi { get; set; }
        public string Vade { get; set; }
        public string Aciklama { get; set; }
        public double Alinan { get; set; }
        public string Personel { get; set; }
    }
}
