//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace istoCPos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int Id { get; set; }
        public string MusteriAdi { get; set; }
        public string Telefon { get; set; }
        public string CepTelefon { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNumarasi { get; set; }
        public string Grup1 { get; set; }
        public string Grup2 { get; set; }
        public string Grup3 { get; set; }
        public string Adres { get; set; }
        public string Sehir { get; set; }
        public string ilce { get; set; }
        public string Ulke { get; set; }
        public string FaturaAdres { get; set; }
        public string e_mail { get; set; }
        public string RiskLimit { get; set; }
        public string FiyatSecenegi { get; set; }
        public string Doviz { get; set; }
        public string Aciklama { get; set; }
        public Nullable<double> Bakiye { get; set; }
        public string Unvan { get; set; }
        public string FirmaAdi { get; set; }
    }
}
