//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace istoCPos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int UrunId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunBarkod { get; set; }
        public string Birim { get; set; }
        public Nullable<double> KdvOrani { get; set; }
        public Nullable<double> KdvTutari { get; set; }
        public Nullable<double> AlisFiyati { get; set; }
        public Nullable<double> SatisFiyati1 { get; set; }
        public Nullable<double> SatisFiyati2 { get; set; }
        public Nullable<double> SatisFiyati3 { get; set; }
        public Nullable<double> SatisFiyati4 { get; set; }
        public string Grup1 { get; set; }
        public string Grup2 { get; set; }
        public string Grup3 { get; set; }
        public string Aciklama { get; set; }
        public Nullable<double> KritikSeviye { get; set; }
        public Nullable<double> MaximumSeviye { get; set; }
        public string Kullanici { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<double> StokMiktari { get; set; }
    }
}
